import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';
import '../services/campaign_service.dart';
class CampaignDetailPage extends StatefulWidget{final Campaign campaign;const CampaignDetailPage({super.key,required this.campaign});@override State<CampaignDetailPage> createState()=>_CampaignDetailPageState();}
class _CampaignDetailPageState extends State<CampaignDetailPage>{bool favorite=false;@override void initState(){super.initState();favorite=CampaignService.instance.isFavorite(widget.campaign.id);}
 Future<void> toggle()async{await CampaignService.instance.toggleFavorite(widget.campaign.id);if(mounted)setState(()=>favorite=!favorite);}
 Future<void> open()async{final uri=Uri.tryParse(widget.campaign.sourceUrl);if(uri!=null&&uri.hasScheme)await launchUrl(uri,mode:LaunchMode.externalApplication);}
 @override Widget build(BuildContext context){final c=widget.campaign;final detail='${c.data['conditions']??c.data['terms']??c.description}'.trim();return Scaffold(backgroundColor:const Color(0xFFF8F7FC),body:SafeArea(child:ListView(padding:EdgeInsets.zero,children:[Padding(padding:const EdgeInsets.symmetric(horizontal:8,vertical:4),child:Row(children:[IconButton(icon:const Icon(Icons.arrow_back_rounded),onPressed:()=>Navigator.pop(context)),const Expanded(child:Center(child:Text('Kampanya Detayı',style:TextStyle(fontWeight:FontWeight.w900,fontSize:16)))),IconButton(icon:Icon(favorite?Icons.favorite:Icons.favorite_border,color:favorite?Colors.redAccent:null),onPressed:toggle)])),Container(margin:const EdgeInsets.fromLTRB(16,4,16,0),height:160,decoration:BoxDecoration(color:c.brandColor,borderRadius:BorderRadius.circular(20)),alignment:Alignment.center,child:Text(c.brand,textAlign:TextAlign.center,style:const TextStyle(color:Colors.white,fontSize:25,fontWeight:FontWeight.w900))),Padding(padding:const EdgeInsets.fromLTRB(20,18,20,0),child:Text(c.title,style:const TextStyle(fontSize:21,fontWeight:FontWeight.w900,color:Color(0xFF211D2D)))),Padding(padding:const EdgeInsets.fromLTRB(20,10,20,0),child:Text(c.description.isEmpty?'Kampanya açıklaması bulunmuyor.':c.description,style:const TextStyle(color:Color(0xFF5F5969),height:1.45))),const Padding(padding:EdgeInsets.fromLTRB(20,18,20,0),child:Divider()),_InfoRow(Icons.local_offer_outlined,'Kategori',c.category),_InfoRow(Icons.account_balance_outlined,'Banka',c.bankName.isEmpty?'Belirtilmemiş':c.bankName),if(c.cardName.isNotEmpty)_InfoRow(Icons.credit_card_outlined,'Kart',c.cardName),if(c.network.isNotEmpty)_InfoRow(Icons.payment_outlined,'Kart ağı',c.network),_InfoRow(Icons.calendar_today_outlined,'Kampanya Tarihleri',c.dateRangeLabel),Padding(padding:const EdgeInsets.fromLTRB(20,12,20,0),child:Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(16),border:Border.all(color:const Color(0xFFE7E1EE))),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Kampanya Detayları',style:TextStyle(fontWeight:FontWeight.w900,fontSize:16)),const SizedBox(height:8),Text(detail.isEmpty?'Detay bulunmuyor.':detail,style:const TextStyle(color:Color(0xFF5F5969),height:1.45))]))),Padding(padding:const EdgeInsets.fromLTRB(20,14,20,0),child:SizedBox(height:52,child:FilledButton.icon(onPressed:c.sourceUrl.isEmpty?null:open,icon:const Icon(Icons.open_in_new_rounded),label:const Text('Kampanyaya Git',style:TextStyle(fontWeight:FontWeight.w900)),style:FilledButton.styleFrom(backgroundColor:const Color(0xFF6D3DF5),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(16))))),),const SizedBox(height:28)])));}
}
class _InfoRow extends StatelessWidget{final IconData icon;final String label,value;const _InfoRow(this.icon,this.label,this.value);@override Widget build(BuildContext context)=>Padding(padding:const EdgeInsets.symmetric(horizontal:20,vertical:8),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(icon,size:20,color:const Color(0xFF777187)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(label,style:const TextStyle(color:Color(0xFF777187),fontSize:11)),const SizedBox(height:2),Text(value,style:const TextStyle(fontWeight:FontWeight.w700,fontSize:14,color:Color(0xFF211D2D)))]))]));}
