import 'package:flutter/material.dart';
import '../services/campaign_service.dart';

class CampaignCard extends StatelessWidget{
  final Campaign campaign; final bool isFavorite; final VoidCallback? onTap; final VoidCallback? onFavoriteTap;
  const CampaignCard({super.key,required this.campaign,this.isFavorite=false,this.onTap,this.onFavoriteTap});
  @override Widget build(BuildContext context)=>Card(margin:const EdgeInsets.symmetric(horizontal:16,vertical:6),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(18),side:const BorderSide(color:Color(0xFFE5DFEB))),clipBehavior:Clip.antiAlias,child:InkWell(onTap:onTap,child:Padding(padding:const EdgeInsets.all(14),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(crossAxisAlignment:CrossAxisAlignment.start,children:[_Logo(campaign.brand,campaign.brandColor),const SizedBox(width:12),Expanded(child:Text(campaign.title,style:const TextStyle(fontWeight:FontWeight.w800,fontSize:15,height:1.25))),const SizedBox(width:8),Column(crossAxisAlignment:CrossAxisAlignment.end,children:[_Badge(campaign.badgeType,campaign.badgeLabel),const SizedBox(height:6),GestureDetector(onTap:onFavoriteTap,child:Icon(isFavorite?Icons.favorite:Icons.favorite_border,size:20,color:isFavorite?Colors.redAccent:const Color(0xFF77717F)))])]),const SizedBox(height:8),Text(campaign.description.isEmpty?'Kampanya detaylarını görmek için dokun.':campaign.description,maxLines:3,overflow:TextOverflow.ellipsis,style:const TextStyle(color:Color(0xFF6F687A),fontSize:12.5,height:1.35)),const SizedBox(height:10),Wrap(spacing:7,runSpacing:6,children:[_Tag(Icons.local_offer_outlined,campaign.category),if(campaign.bankName.isNotEmpty)_Tag(Icons.account_balance_outlined,campaign.bankName),if(campaign.cardName.isNotEmpty)_Tag(Icons.credit_card_outlined,campaign.cardName)]),const SizedBox(height:11),Align(alignment:Alignment.centerRight,child:ElevatedButton.icon(onPressed:onTap,style:ElevatedButton.styleFrom(backgroundColor:const Color(0xFF6D3DF5),foregroundColor:Colors.white,elevation:0,padding:const EdgeInsets.symmetric(horizontal:15,vertical:9),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(11))),icon:const Text('Detaylar',style:TextStyle(fontSize:12.5,fontWeight:FontWeight.w800)),label:const Icon(Icons.arrow_forward,size:16))) ]))));
}
class _Logo extends StatelessWidget{final String text;final Color color;const _Logo(this.text,this.color);@override Widget build(BuildContext context)=>Container(width:48,height:48,decoration:BoxDecoration(color:color,borderRadius:BorderRadius.circular(12)),alignment:Alignment.center,child:Text(text.isEmpty?'?':text.substring(0,1).toUpperCase(),style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w900,fontSize:18)));}
class _Badge extends StatelessWidget{final BadgeType type;final String label;const _Badge(this.type,this.label);@override Widget build(BuildContext context){final urgent=type==BadgeType.urgent;return Container(padding:const EdgeInsets.symmetric(horizontal:8,vertical:4),decoration:BoxDecoration(color:urgent?const Color(0xFFFDEAEA):const Color(0xFFE9F6EC),borderRadius:BorderRadius.circular(20)),child:Row(mainAxisSize:MainAxisSize.min,children:[Icon(Icons.access_time,size:11,color:urgent?const Color(0xFFD32F2F):const Color(0xFF2E7D32)),const SizedBox(width:3),Text(label,style:TextStyle(color:urgent?const Color(0xFFD32F2F):const Color(0xFF2E7D32),fontSize:10.5,fontWeight:FontWeight.w800))]));}}
class _Tag extends StatelessWidget{final IconData icon;final String label;const _Tag(this.icon,this.label);@override Widget build(BuildContext context)=>Container(padding:const EdgeInsets.symmetric(horizontal:8,vertical:5),decoration:BoxDecoration(color:const Color(0xFFF1EFF5),borderRadius:BorderRadius.circular(8)),child:Row(mainAxisSize:MainAxisSize.min,children:[Icon(icon,size:12,color:const Color(0xFF77717F)),const SizedBox(width:4),Text(label,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:10.5,color:Color(0xFF77717F))) ]));}
