from pathlib import Path
import re
p=Path('lib/main.dart')
s=p.read_text(encoding='utf-8')
repls={'0xFF8B5CF6':'0xFF6366F1','0xFF9B7CFF':'0xFF6366F1','0xFF35245F':'0xFF27306B','0xFFC4B5FD':'0xFF885CF6','0xFF15121E':'0xFF111827','0xFF211C2D':'0xFF1E293B','0xFF51466A':'0xFF3B4565','0xFF0D0B14':'0xFF0F172A','0xFF171421':'0xFF111827','0xFF292238':'0xFF293554','0xFF302842':'0xFF33415F','0xFF191622':'0xFF172033','0xFF5B3FA8':'0xFF3949A3','0xFF342B48':'0xFF33415F','0xFF110E18':'0xFF0B1220','0xFF49317A':'0xFF4B3CC4','0xFF8062E8':'0xFF6366F1'}
for a,b in repls.items(): s=s.replace(a,b)
s=s.replace('margin: const EdgeInsets.only(bottom: 14),','margin: const EdgeInsets.only(bottom: 8),',1)
s=s.replace('padding: const EdgeInsets.all(14),\n        child: Column(','padding: const EdgeInsets.fromLTRB(10, 9, 10, 10),\n        child: Column(',1)
marker='class SmartCampaignCard extends StatelessWidget {'
if '_MerchantLogo extends StatelessWidget' not in s:
 h='''String? _merchantDomain(String merchant) {\n  final m = _norm(merchant);\n  const domains = <String,String>{\n    'migros':'migros.com.tr','shell':'shell.com.tr','opet':'opet.com.tr','petrol ofisi':'petrolofisi.com.tr','boyner':'boyner.com.tr','trendyol':'trendyol.com','hepsiburada':'hepsiburada.com','amazon':'amazon.com.tr','n11':'n11.com','a101':'a101.com.tr','bim':'bim.com.tr','carrefour':'carrefoursa.com','starbucks':'starbucks.com.tr','nike':'nike.com','apple':'apple.com','teknosa':'teknosa.com','vatan':'vatanbilgisayar.com','mediamarkt':'mediamarkt.com.tr','lc waikiki':'lcwaikiki.com','mavi':'mavi.com','zara':'zara.com','ikea':'ikea.com.tr','pegasus':'flypgs.com','thy':'turkishairlines.com','booking':'booking.com','spotify':'spotify.com','netflix':'netflix.com','steam':'steampowered.com','gastroclub':'gastroclub.com.tr','muhiku':'muhiku.com','enuygun':'enuygun.com',\n  };\n  if (domains.containsKey(m)) return domains[m];\n  for (final e in domains.entries) { if (m.contains(e.key)) return e.value; }\n  return null;\n}\n\nclass _MerchantLogo extends StatelessWidget {\n  final String merchant;\n  const _MerchantLogo({required this.merchant});\n  @override\n  Widget build(BuildContext context) {\n    final domain=_merchantDomain(merchant);\n    final fallback=Container(width:42,height:42,decoration:BoxDecoration(borderRadius:BorderRadius.circular(12),color:Theme.of(context).colorScheme.surfaceContainerHighest),child:Icon(Icons.storefront_rounded,color:Theme.of(context).colorScheme.primary));\n    if(domain==null) return fallback;\n    return ClipRRect(borderRadius:BorderRadius.circular(12),child:Container(width:42,height:42,padding:const EdgeInsets.all(5),color:Colors.white,child:Image.network('https://www.google.com/s2/favicons?domain=$domain&sz=128',fit:BoxFit.contain,errorBuilder:(_,__,___)=>Icon(Icons.storefront_rounded,color:Theme.of(context).colorScheme.primary))));\n  }\n}\n\n'''
 s=s.replace(marker,h+marker)
pattern=re.compile(r'''            Row\(\n              children: \[\n                Icon\(\n                  cards\.isNotEmpty\n                      \? Icons\.emoji_events\n                      : Icons\.local_offer,\n                \),\n\n                const SizedBox\(width: 8\),\n\n                Expanded\(\n  child: Text\(\n    decodeHtmlEntities\(\n      campaign\['title'\]\?\.toString\(\)\.trim\(\) \?\? '',\n    \),\n    style: const TextStyle\(\n      fontSize: 17,\n      fontWeight: FontWeight\.bold,\n    \),\n  \),\n\),''')
r='''            Row(\n              crossAxisAlignment: CrossAxisAlignment.start,\n              children: [\n                if (merchant.isNotEmpty) ...[\n                  _MerchantLogo(merchant: merchant),\n                  const SizedBox(width: 9),\n                ] else ...[\n                  Icon(cards.isNotEmpty ? Icons.emoji_events : Icons.local_offer, size: 25),\n                  const SizedBox(width: 8),\n                ],\n                Expanded(\n                  child: Text(\n                    campaignTitle.isNotEmpty ? campaignTitle : '$merchant Kampanyası',\n                    maxLines: 3,\n                    overflow: TextOverflow.ellipsis,\n                    style: const TextStyle(fontSize: 15.5, height: 1.2, fontWeight: FontWeight.w800),\n                  ),\n                ),'''
s,n=pattern.subn(r,s,count=1)
if n!=1: raise SystemExit('title row patch not found')
s=s.replace('onPressed: onFavorite,\n                  icon: Icon(','onPressed: onFavorite,\n                  constraints: const BoxConstraints(minWidth: 36, minHeight: 36),\n                  padding: EdgeInsets.zero,\n                  icon: Icon(',1)
s=s.replace('onPressed: onCompare,\n                  icon: Icon(','onPressed: onCompare,\n                  constraints: const BoxConstraints(minWidth: 36, minHeight: 36),\n                  padding: EdgeInsets.zero,\n                  icon: Icon(',1)
s=s.replace('padding: const EdgeInsets.only(top: 2),\n                child: Wrap(\n                  spacing: 6,\n                  runSpacing: 6,','padding: const EdgeInsets.only(top: 5),\n                child: Wrap(\n                  spacing: 5,\n                  runSpacing: 4,',1)
s=s.replace("'ℹ️ Bu kampanya kayıtlı kartlarınla eşleşmiyor.'","'ℹ️ Kayıtlı kartlarınla eşleşmiyor'",1)
p.write_text(s,encoding='utf-8')
print('v12 UI applied')
