from pathlib import Path
import re

p = Path('lib/main.dart')
s = p.read_text(encoding='utf-8')

# The generated in-page campaign selector is no longer needed because the
# main shell has dedicated Kartıma Uygun / Tüm Kampanyalar destinations.
# Remove that fragile generated block completely.
needle = "Text('Kartıma Uygun'"
idx = s.find(needle)
if idx >= 0:
    block_start = s.rfind('\n        Container(', 0, idx)
    block_end = s.find('\n        if(widget.cards.isEmpty && !showAllCampaigns)', idx)
    if block_start >= 0 and block_end > block_start:
        s = s[:block_start] + '\n        const SizedBox(height: 4),' + s[block_end:]
        print('removed fragile generated in-page campaign selector')

# Rebuild MyCardsPage with deliberately expanded, balanced Dart. This fixes
# the malformed ListView/map expression generated by the compact patch.
mm = re.search(r'class\s+MyCardsPage\b[^\n{]*\{', s)
cm = re.search(r'class\s+CategoriesPage\s+extends\s+StatelessWidget\s*\{', s)
if mm and cm and cm.start() > mm.start():
    my = '''class MyCardsPage extends StatefulWidget {
  final List<UserCard> cards;
  final Future<void> Function(UserCard) onAdd;
  final Future<void> Function(UserCard) onDelete;

  const MyCardsPage({
    super.key,
    required this.cards,
    required this.onAdd,
    required this.onDelete,
  });

  @override
  State<MyCardsPage> createState() => _MyCardsPageState();
}

class _MyCardsPageState extends State<MyCardsPage> {
  Future<void> addCard() async {
    String bank = 'Akbank';
    String card = 'Axess';
    String network = 'Visa';
    String customerType = 'Bireysel';
    String cardType = 'Kredi';

    const banks = [
      'Akbank', 'Garanti BBVA', 'Yapı Kredi', 'İş Bankası',
      'Ziraat Bankası', 'Halkbank', 'QNB', 'TEB', 'VakıfBank',
      'DenizBank', 'ING', 'HSBC', 'Kuveyt Türk', 'Türkiye Finans',
    ];
    const cardPrograms = [
      'Axess', 'Bonus', 'World', 'Maximum', 'Paraf', 'Bankkart',
      'CardFinans', 'Sağlam Kart', 'CEPTETEB', 'Maximum Genç', 'Bankkart Genç',
    ];
    const networks = ['Visa', 'Mastercard', 'Troy'];
    const customerTypes = ['Bireysel', 'Ticari'];
    const cardTypes = ['Kredi', 'Banka'];

    final result = await showDialog<Map<String, String>>(
      context: context,
      builder: (dialogContext) => StatefulBuilder(
        builder: (dialogContext, setDialog) {
          return AlertDialog(
            title: const Text('Kart Ekle'),
            content: SingleChildScrollView(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  DropdownButtonFormField<String>(
                    value: bank,
                    decoration: const InputDecoration(labelText: 'Banka'),
                    items: banks.map((x) => DropdownMenuItem(value: x, child: Text(x))).toList(),
                    onChanged: (v) { if (v != null) setDialog(() => bank = v); },
                  ),
                  const SizedBox(height: 10),
                  DropdownButtonFormField<String>(
                    value: card,
                    decoration: const InputDecoration(labelText: 'Kart Programı'),
                    items: cardPrograms.map((x) => DropdownMenuItem(value: x, child: Text(x))).toList(),
                    onChanged: (v) { if (v != null) setDialog(() => card = v); },
                  ),
                  const SizedBox(height: 10),
                  DropdownButtonFormField<String>(
                    value: network,
                    decoration: const InputDecoration(labelText: 'Kart Ağı'),
                    items: networks.map((x) => DropdownMenuItem(value: x, child: Text(x))).toList(),
                    onChanged: (v) { if (v != null) setDialog(() => network = v); },
                  ),
                  const SizedBox(height: 10),
                  DropdownButtonFormField<String>(
                    value: customerType,
                    decoration: const InputDecoration(labelText: 'Müşteri Tipi'),
                    items: customerTypes.map((x) => DropdownMenuItem(value: x, child: Text(x))).toList(),
                    onChanged: (v) { if (v != null) setDialog(() => customerType = v); },
                  ),
                  const SizedBox(height: 10),
                  DropdownButtonFormField<String>(
                    value: cardType,
                    decoration: const InputDecoration(labelText: 'Kart Tipi'),
                    items: cardTypes.map((x) => DropdownMenuItem(value: x, child: Text(x))).toList(),
                    onChanged: (v) { if (v != null) setDialog(() => cardType = v); },
                  ),
                ],
              ),
            ),
            actions: [
              TextButton(
                onPressed: () => Navigator.pop(dialogContext),
                child: const Text('İptal'),
              ),
              FilledButton(
                onPressed: () => Navigator.pop(dialogContext, {
                  'bank': bank,
                  'card': card,
                  'network': network,
                  'customerType': customerType,
                  'cardType': cardType,
                }),
                child: const Text('Kaydet'),
              ),
            ],
          );
        },
      ),
    );

    if (result == null || !mounted) return;
    try {
      await widget.onAdd(UserCard(
        id: '',
        bank: result['bank']!,
        card: result['card']!,
        network: result['network']!,
        customerType: result['customerType']!,
        cardType: result['cardType']!,
      ));
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Kart eklendi')),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Kart eklenemedi: $e')),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text(
          'Bendeki Kartlar',
          style: TextStyle(fontSize: 23, fontWeight: FontWeight.w900),
        ),
        actions: [
          IconButton(
            onPressed: addCard,
            icon: const Icon(Icons.add_circle_outline_rounded),
          ),
        ],
      ),
      body: widget.cards.isEmpty
          ? Center(
              child: FilledButton.icon(
                onPressed: addCard,
                icon: const Icon(Icons.add),
                label: const Text('Kart Ekle'),
              ),
            )
          : ListView.builder(
              padding: const EdgeInsets.all(14),
              itemCount: widget.cards.length,
              itemBuilder: (context, index) {
                final x = widget.cards[index];
                return Card(
                  child: ListTile(
                    leading: CatalogLogo(label: x.bank),
                    title: Text('${x.bank} • ${x.card}'),
                    subtitle: Text('${x.network} • ${x.customerType} • ${x.cardType}'),
                    trailing: IconButton(
                      onPressed: () { widget.onDelete(x); },
                      icon: const Icon(Icons.delete_outline),
                    ),
                  ),
                );
              },
            ),
      floatingActionButton: FloatingActionButton(
        onPressed: addCard,
        child: const Icon(Icons.add),
      ),
    );
  }
}
'''
    s = s[:mm.start()] + my + s[cm.start():]
    print('rebuilt MyCardsPage with balanced Dart')

p.write_text(s, encoding='utf-8')
print('final v16 Dart safety pass complete')
